name: milkroute_tecnico
description: "A new Flutter project."
publish_to: 'none'
version: 2.0.1

environment:
  sdk: ^3.6.1

dependencies:
  animations: ^2.0.11
  
  camera: ^0.11.1
  connectivity_plus: ^6.1.3
  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_easyloading: ^3.0.5
  flutter_localization: ^0.3.1
  flutter_pdfview: ^1.4.0
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.17
  form_field_validator: ^1.1.0
  geolocator: ^13.0.2
  google_nav_bar: ^5.0.7
  http: ^1.3.0
  image: ^4.5.3
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  local_auth: ^2.3.0
  maps_launcher: ^3.0.0+1
  month_picker_dialog: ^6.0.3
  path_provider: ^2.1.5
  pdf: ^3.11.2
  percent_indicator: ^4.2.4
  provider: ^6.1.2
  reflectable: ^4.0.12
  share_plus: ^10.1.4
  shared_preferences: ^2.5.2
  signature: ^5.5.0
  sqflite: ^2.4.1
  table_calendar: ^3.1.3
  url_launcher: ^6.3.1
  # persist_theme: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.4
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/gifs/  
